-- =========================================
-- 1) テーブル作成
-- =========================================
create table if not exists public.jobs (
  -- id: 各求人を一意に識別する番号
  -- bigint: 大きい整数型
  -- generated by default as identity: 自動採番（1,2,3...）する
  -- primary key: 主キー（一意・NULL不可）
  id bigint generated by default as identity primary key,

  -- category: 求人カテゴリ（文字列）
  -- text: 文字列型
  -- not null: 必須項目（空は不可）
  category text not null,

  -- salary: 年収（万円）
  -- integer: 整数型
  -- check (salary > 0): 0以下は保存不可
  salary integer not null check (salary > 0),

  -- title: 求人タイトル（文字列）
  title text not null,

  -- created_at: 作成日時
  -- timestamptz: タイムゾーン付き日時
  -- default timezone('utc'::text, now()):
  --   値が渡されなかったら「現在時刻(UTC)」を自動で入れる
  created_at timestamptz not null default timezone('utc'::text, now())
);

-- =========================================
-- 2) RLS (Row Level Security) を有効化
-- =========================================
alter table public.jobs enable row level security;

-- =========================================
-- 3) 読み取り(SELECT)ポリシー
-- =========================================
-- 既に同名ポリシーがあれば削除（再実行しやすくするため）
drop policy if exists "Allow public read jobs" on public.jobs;

-- policy作成
create policy "Allow public read jobs"
  on public.jobs            -- どのテーブルに対して
  for select                -- 何を許可するか（読み取り）
  to anon, authenticated    -- 誰に許可するか（未ログイン/ログイン）
  using (true);             -- どの行を許可するか（true = 全行）

-- =========================================
-- 4) 書き込み(INSERT)ポリシー
-- =========================================
drop policy if exists "Allow public insert jobs" on public.jobs;

create policy "Allow public insert jobs"
  on public.jobs
  for insert                -- 新規追加を許可
  to anon, authenticated
  with check (true);        -- 追加時の条件（true = 条件なしで許可）

-- =========================================
-- 5) 初期データ投入（学習用）
-- =========================================
insert into public.jobs (category, salary, title)
values
  ('エンジニア', 700, '経験者歓迎！大手企業でのWebエンジニア募集'),
  ('営業', 350, '未経験OK！営業アシスタント急募'),
  ('マーケティング', 800, 'グローバル企業でのマーケティングマネージャー'),
  ('デザイン', 550, 'UI/UXデザイナー募集！急成長中のスタートアップ'),
  ('製造', 650, '大手製造業での生産管理スペシャリスト'),
  ('財務・経理', 700, '急成長ベンチャーでの経理マネージャー募集'),
  ('人事', 500, '大手IT企業での人事担当者募集'),
  ('カスタマーサポート', 400, '外資系企業でのカスタマーサポート担当募集'),
  ('財務・経理', 550, '簿記資格者！大学病院での勤務'),
  ('事務', 300, '一般事務スタッフ募集！週3日からOK')
on conflict do nothing;

-- NOTE:
-- on conflict do nothing は「一意制約などで衝突した時だけスキップ」です。
-- 現在の定義だと title に一意制約がないので、再実行すると重複行が入り得ます。
